# Generated by Django 5.1.2 on 2024-10-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='device_photo/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_memory', models.IntegerField(blank=True, null=True)),
                ('storage_memory', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('booking_start_time', models.DateTimeField(blank=True, null=True)),
                ('booking_end_time', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
